# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.7.2"

FABRIC8_VERSION="2.2.1"

$provisionScript = <<SCRIPT
if [ -d '/var/lib/openshift' ]; then
  exit 0
fi

yum remove -y docker-logrotate
yum install -y http://cbs.centos.org/kojifiles/packages/docker/1.6.2/3.gitc3ca5bb.el7/x86_64/docker-1.6.2-3.gitc3ca5bb.el7.x86_64.rpm

systemctl restart docker.service

mkdir /tmp/openshift
echo "Downloading OpenShift binaries..."
curl -sSL https://github.com/openshift/origin/releases/download/v0.6.2/openshift-origin-v0.6.2-6a30f4d-linux-amd64.tar.gz | tar xzv -C /tmp/openshift
mv /tmp/openshift/* /usr/bin/

mkdir /var/lib/openshift
restorecon -v /var/lib/openshift

cat <<EOF > /usr/lib/systemd/system/openshift.service
[Unit]
Description=OpenShift
Requires=docker.service network.service
After=network.service
[Service]
ExecStart=/usr/bin/openshift start --master=172.28.128.4 --cors-allowed-origins=.*
WorkingDirectory=/var/lib/openshift/
[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable openshift.service
systemctl start openshift.service

mkdir -p ~/.kube/
ln -s /var/lib/openshift/openshift.local.config/master/admin.kubeconfig ~/.kube/config

while true; do
  curl -k -s -f -o /dev/null --connect-timeout 1 https://localhost:8443/healthz/ready && break || sleep 1
done

oadm policy add-cluster-role-to-user cluster-admin admin
oadm router --create --credentials=/var/lib/openshift/openshift.local.config/master/openshift-router.kubeconfig
oadm registry --create --credentials=/var/lib/openshift/openshift.local.config/master/openshift-registry.kubeconfig
oadm new-project fabric8 --description="fabric8 Apps"

oc delete scc restricted
cat <<EOF | oc create -f -
---
  apiVersion: v1
  groups:
  - system:authenticated
  kind: SecurityContextConstraints
  metadata:
    name: restricted
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: MustRunAs
EOF

oc delete scc privileged
cat <<EOF | oc create -f -
---
  allowHostDirVolumePlugin: true
  allowPrivilegedContainer: true
  apiVersion: v1
  groups:
  - system:cluster-admins
  - system:nodes
  kind: SecurityContextConstraints
  metadata:
    name: privileged
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: RunAsAny
  users:
  - system:serviceaccount:openshift-infra:build-controller
  - system:serviceaccount:default:default
  - system:serviceaccount:default:fabric8
EOF

cat <<EOF | oc create -f -
---
  apiVersion: "v1"
  kind: "Secret"
  metadata:
    name: "openshift-cert-secrets"
  data:
    root-cert: "$(base64 -w 0 /var/lib/openshift/openshift.local.config/master/ca.crt)"
    admin-cert: "$(base64 -w 0 /var/lib/openshift/openshift.local.config/master/admin.crt)"
    admin-key: "$(base64 -w 0 /var/lib/openshift/openshift.local.config/master/admin.key)"
EOF

cat <<EOF | oc create -f -
---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: fabric8
  secrets:
    -
      name: openshift-cert-secrets
EOF

# Create route to registry. Please not that this route can be used for applications to find
# the images. Since it goes through the router this is not optimal for production setups
# when internally images are fetched. 
cat <<EOF | oc create -f -
{
    "kind": "Route",
    "apiVersion": "v1",
    "metadata": {
        "name": "docker-registry-route"
    },
    "spec": {
        "host": "docker-registry.vagrant.local",
        "to": {
            "kind": "Service",
            "name": "docker-registry"
        }
    }
}
EOF
echo "127.0.0.1    docker-registry.vagrant.local" >> /etc/hosts

export FABRIC8_VERSION=${FABRIC8_VERSION:=2.2.1}
echo "Installing templates from fabric8 version ${FABRIC8_VERSION}"
for app in base management logging metrics cdelivery-core cdelivery ipaas kitchen-sink; do
  echo "Installing ${app} template"
  oc create -f http://central.maven.org/maven2/io/fabric8/apps/${app}/${FABRIC8_VERSION}/${app}-${FABRIC8_VERSION}-kubernetes.json
done

# now lets instantiate the console
oc process base | oc create -f -

# now lets create a route for it:
cat <<EOF | oc create -f -
{
    "kind": "Route",
    "apiVersion": "v1",
    "metadata": {
        "name": "fabric8"
    },
    "spec": {
        "host": "fabric8.vagrant.local",
        "to": {
            "kind": "Service",
            "name": "fabric8"
        }
    }
}
EOF

echo
echo
echo Now we need to wait for the fabric8 pod to startup.
echo This will take a few minutes as it downloads the docker image.
echo Please be patient!
echo
echo You can watch progress by typing the following commands:
echo
echo "    oc login --insecure-skip-tls-verify=false https://172.28.128.4:8443"
echo
echo Then enter admin/admin for user/password.
echo Now to see the status of the system:
echo
echo "    oc get pods"
echo
echo or you can watch from the command line via one of these commands:
echo
echo "    watch oc get pods"
echo
echo Now waiting for the fabric8 pod to start Running....

until oc get pods -l component=console,provider=fabric8  | grep -m 1 "Running"; do sleep 1 ; done

echo
echo --------------------------------------------------------------
echo Fabric8 pod is running! Who-hoo!
echo --------------------------------------------------------------
echo
echo
echo Now open the fabric8 console at:
echo
echo "    http://fabric8.vagrant.local/"
echo
echo When you first open your browser Chrome will say:
echo
echo "   Your connection is not private"
echo
echo * Don't panic!
echo
echo * Click on the small 'Advanced' link on the bottom right
echo
echo * Now click on the link that says 'Proceed to fabric8.vagrant.local (unsafe)' bottom right
echo
echo * Now the browser should redirect to the login page. Enter admin/admin
echo
echo * Now the browser should redirect to the login page. Enter admin/admin
echo
echo * You should now be in the main fabric8 console. That was easy eh! :)
echo
echo * Make sure you start off in the 'default' namespace.
echo
echo
echo To install more applications click the Run... button on the Apps tab.
echo
echo We love feedback: http://fabric8.io/community/
echo Have fun!

SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.hostmanager.aliases = %w(vagrant.local fabric8.vagrant.local fabric8-master.vagrant.local jenkins.vagrant.local gogs.vagrant.local nexus.vagrant.local hubot-web-hook.vagrant.local letschat.vagrant.local kibana.vagrant.local taiga.vagrant.local fabric8-forge.vagrant.local)


  config.vm.box = "jimmidyson/centos-7.1"
  config.vm.box_version = "= 1.0.2"

  config.vm.network "private_network", ip: "172.28.128.4"

  config.vm.hostname = "fabric8-master.vagrant.local"


  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end


  config.vm.provision "shell", inline: $provisionScript

end
